debug: true
log_level: info
http_listen: ":3030"
dir_path: "path/to/dir"
clean_api_url: "http-url" # will request with PUT method, and send ["fil1", "fil2", ...] json-data
img:
  max_width: 1000 # in pixels, not required
  max_height: 1000 # in pixels, not required
