definitions:
  dopTypes.ErrRep:
    properties:
      desc:
        type: string
      error_code:
        type: string
      fields:
        additionalProperties:
          type: string
        type: object
    type: object
  multipart.FileHeader:
    properties:
      filename:
        type: string
      header:
        $ref: '#/definitions/textproto.MIMEHeader'
      size:
        type: integer
    type: object
  rest.SaveRepSt:
    properties:
      path:
        type: string
    type: object
  rest.SaveReqSt:
    properties:
      dir:
        type: string
      extract_zip:
        type: boolean
      file:
        $ref: '#/definitions/multipart.FileHeader'
      no_cut:
        type: boolean
    required:
    - dir
    - file
    type: object
  textproto.MIMEHeader:
    additionalProperties:
      items:
        type: string
      type: array
    type: object
info:
  contact: {}
paths:
  /:
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: body
        in: body
        name: body
        schema:
          $ref: '#/definitions/rest.SaveReqSt'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rest.SaveRepSt'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dopTypes.ErrRep'
      summary: Upload and save file.
      tags:
      - main
  /:path:
    get:
      parameters:
      - description: path
        in: path
        name: path
        required: true
        type: string
      - in: query
        name: download
        type: string
      - in: query
        name: h
        type: integer
      - in: query
        name: m
        type: string
      - in: query
        name: w
        type: integer
      produces:
      - application/octet-stream
      responses:
        "200":
          description: ""
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dopTypes.ErrRep'
      summary: Get or download file.
      tags:
      - main
swagger: "2.0"
